### ISSUE TITLE
Error while compiling bgpq3

### ISSUE THREAD

**Issue by detzen** [peering-manager/bgpq-proxy#9] opened 2021-11-03 20:11 UTC
Hi,

when I try to turn up bgpq-proxy, compilation of bgpq3 fails and container could not be built
```
$ docker build -t bgpq-proxy .
Sending build context to Docker daemon  48.64kB
Step 1/20 : FROM python:3.9-alpine AS builder
3.9-alpine: Pulling from library/python
a0d0a0d46f8b: Already exists
ba51967de001: Already exists
472f8c18fd1c: Already exists
02e5da7e751e: Already exists
0da47f71280c: Already exists
Digest: sha256:a31add3a2442bceecb9d4f66e575072c4d4a1c7e561b7fe44cdf0dd277685276
Status: Downloaded newer image for python:3.9-alpine
 ---> 2621d3bd4b02
Step 2/20 : RUN mkdir app &&     apk add --no-cache build-base autoconf automake gcc git linux-headers musl-dev
 ---> Running in 14193fecb2f6
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
(1/33) Installing m4 (1.4.18-r2)
(2/33) Installing perl (5.32.1-r0)
(3/33) Installing autoconf (2.71-r0)
(4/33) Installing automake (1.16.3-r0)
(5/33) Installing libgcc (10.3.1_git20210424-r2)
(6/33) Installing libstdc++ (10.3.1_git20210424-r2)
(7/33) Installing binutils (2.35.2-r2)
(8/33) Installing libmagic (5.40-r1)
(9/33) Installing file (5.40-r1)
(10/33) Installing libgomp (10.3.1_git20210424-r2)
(11/33) Installing libatomic (10.3.1_git20210424-r2)
(12/33) Installing libgphobos (10.3.1_git20210424-r2)
(13/33) Installing gmp (6.2.1-r0)
(14/33) Installing isl22 (0.22-r0)
(15/33) Installing mpfr4 (4.1.0-r0)
(16/33) Installing mpc1 (1.2.1-r0)
(17/33) Installing gcc (10.3.1_git20210424-r2)
(18/33) Installing musl-dev (1.2.2-r3)
(19/33) Installing libc-dev (0.7.2-r3)
(20/33) Installing g++ (10.3.1_git20210424-r2)
(21/33) Installing make (4.3-r0)
(22/33) Installing fortify-headers (1.1-r1)
(23/33) Installing patch (2.7.6-r7)
(24/33) Installing build-base (0.5-r2)
(25/33) Installing brotli-libs (1.0.9-r5)
(26/33) Installing nghttp2-libs (1.43.0-r0)
(27/33) Installing libcurl (7.79.1-r0)
(28/33) Installing pcre2 (10.36-r0)
(29/33) Installing git (2.32.0-r0)
(30/33) Installing perl-error (0.17029-r1)
(31/33) Installing perl-git (2.32.0-r0)
(32/33) Installing git-perl (2.32.0-r0)
(33/33) Installing linux-headers (5.10.41-r0)
Executing busybox-1.33.1-r3.trigger
OK: 266 MiB in 69 packages
Removing intermediate container 14193fecb2f6
 ---> 2b8824d46652
Step 3/20 : WORKDIR /app
 ---> Running in 5a27d4fd458c
Removing intermediate container 5a27d4fd458c
 ---> 67e04e0f0580
Step 4/20 : COPY . /app
 ---> 19554b27e36e
Step 5/20 : RUN pip install -U pip wheel &&     pip install -U -r requirements.txt &&     pip install 'uwsgi>=2.0,<2.1'
 ---> Running in 2b82dceaa57a
Requirement already satisfied: pip in /usr/local/lib/python3.9/site-packages (21.2.4)
Collecting pip
  Downloading pip-21.3.1-py3-none-any.whl (1.7 MB)
Requirement already satisfied: wheel in /usr/local/lib/python3.9/site-packages (0.37.0)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.2.4
    Uninstalling pip-21.2.4:
      Successfully uninstalled pip-21.2.4
Successfully installed pip-21.3.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Collecting flask-restful
  Downloading Flask_RESTful-0.3.9-py2.py3-none-any.whl (25 kB)
Collecting redis
  Downloading redis-3.5.3-py2.py3-none-any.whl (72 kB)
Collecting pytz
  Downloading pytz-2021.3-py2.py3-none-any.whl (503 kB)
Collecting aniso8601>=0.82
  Downloading aniso8601-9.0.1-py2.py3-none-any.whl (52 kB)
Collecting six>=1.3.0
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting Flask>=0.8
  Downloading Flask-2.0.2-py3-none-any.whl (95 kB)
Collecting itsdangerous>=2.0
  Downloading itsdangerous-2.0.1-py3-none-any.whl (18 kB)
Collecting click>=7.1.2
  Downloading click-8.0.3-py3-none-any.whl (97 kB)
Collecting Werkzeug>=2.0
  Downloading Werkzeug-2.0.2-py3-none-any.whl (288 kB)
Collecting Jinja2>=3.0
  Downloading Jinja2-3.0.2-py3-none-any.whl (133 kB)
Collecting MarkupSafe>=2.0
  Downloading MarkupSafe-2.0.1-cp39-cp39-musllinux_1_1_x86_64.whl (30 kB)
Installing collected packages: MarkupSafe, Werkzeug, Jinja2, itsdangerous, click, six, pytz, Flask, aniso8601, redis, flask-restful
Successfully installed Flask-2.0.2 Jinja2-3.0.2 MarkupSafe-2.0.1 Werkzeug-2.0.2 aniso8601-9.0.1 click-8.0.3 flask-restful-0.3.9 itsdangerous-2.0.1 pytz-2021.3 redis-3.5.3 six-1.16.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Collecting uwsgi<2.1,>=2.0
  Downloading uwsgi-2.0.20.tar.gz (804 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: uwsgi
  Building wheel for uwsgi (setup.py): started
  Building wheel for uwsgi (setup.py): finished with status 'done'
  Created wheel for uwsgi: filename=uWSGI-2.0.20-cp39-cp39-linux_x86_64.whl size=521366 sha256=04cb0084005f7948c2a98bfa40a5aa6c3ceb662571027360fe9890c5d97ab8e5
  Stored in directory: /root/.cache/pip/wheels/09/ac/7b/80681f729cf8c820803228c8752d49581afd6a446bc58b172c
Successfully built uwsgi
Installing collected packages: uwsgi
Successfully installed uwsgi-2.0.20
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Removing intermediate container 2b82dceaa57a
 ---> 145f2952e7ff
Step 6/20 : FROM builder AS bgpq3_builder
 ---> 145f2952e7ff
Step 7/20 : WORKDIR /bgp3
 ---> Running in 260e2ccfb645
Removing intermediate container 260e2ccfb645
 ---> 7780ca3c4a14
Step 8/20 : RUN mkdir /bgpq3 &&     git clone https://github.com/snar/bgpq3 . && git checkout v0.1.35 &&     ./configure && make install
 ---> Running in 6e8265e70622
Cloning into '.'...
Note: switching to 'v0.1.35'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 07246c9 make GCC happy
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for a BSD-compatible install... /usr/bin/install -c
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking sys/cdefs.h usability... no
checking sys/cdefs.h presence... no
checking for sys/cdefs.h... no
checking sys/queue.h usability... no
checking sys/queue.h presence... no
checking for sys/queue.h... no
checking sys/tree.h usability... no
checking sys/tree.h presence... no
checking for sys/tree.h... no
checking sys/select.h usability... yes
checking sys/select.h presence... yes
checking for sys/select.h... yes
checking for STAILQ_ interface in queue.h... yes
checking for markdown_py... no
checking for markdown2... no
checking for markdown... no
checking for strlcpy... yes
checking for socket in -lsocket... no
checking for getaddrinfo in -lnsl... no
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config.h
gcc -g -O2 -DHAVE_CONFIG_H -g -Wall -I. -O0 -c bgpq3.c
make: gcc: Operation not permitted
make: *** [Makefile:26: bgpq3.o] Error 127
The command '/bin/sh -c mkdir /bgpq3 &&     git clone https://github.com/snar/bgpq3 . && git checkout v0.1.35 &&     ./configure && make install' returned a non-zero code: 2
```

docker version is 19.03.8

Regards,
Alex

**Comment by gmazoyer** [comment] 2021-11-04 23:27
Weird. I cannot reproduce this issue. Can you try after updating to 8940bea?

**Comment by detzen** [comment] 2021-11-08 21:25
It seems, there is a problem withe the docker installation on one of my machines. I just tried building the image on a fresh installed machine. There it works. Sorry for the inconveniences.
Regards,
Alex

**Comment by gmazoyer** [comment] 2021-11-08 21:39
Thanks for the feedback. Closing.

**Closed by gmazoyer** 2021-11-08 21:39 UTC
Labels: status: invalid
